# Generated by Django 4.1.3 on 2022-11-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer_tourist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("father_name", models.CharField(default="", max_length=50)),
                ("email", models.CharField(default="", max_length=50)),
                ("password", models.CharField(default="", max_length=50)),
                ("age", models.CharField(default="", max_length=50)),
                ("gender", models.CharField(default="", max_length=50)),
                ("cnic", models.CharField(default="", max_length=50)),
                ("phone_no", models.IntegerField(default="", max_length=11)),
                ("dececription", models.TextField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="tour_package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("phone_no", models.IntegerField(default="", max_length=11)),
                ("room_no", models.IntegerField(default="", max_length=3)),
                ("days_of_stay", models.IntegerField(default="", max_length=3)),
                ("tourpackagedetail", models.CharField(default="", max_length=50)),
                ("transportdetail", models.CharField(default="", max_length=50)),
                ("tourareadetail", models.CharField(default="", max_length=50)),
                ("email", models.CharField(default="", max_length=50)),
                ("password", models.CharField(default="", max_length=50)),
                ("age", models.CharField(default="", max_length=50)),
                ("gender", models.CharField(default="", max_length=50)),
            ],
        ),
    ]
