# Generated by Django 4.1.3 on 2022-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gul_e_ruf_ruf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_no",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="foodpackage",
            name="phone_no",
            field=models.CharField(default="", max_length=11),
        ),
    ]
